### ISSUE TITLE
Generating a supervised dataset

### ISSUE THREAD

**Issue by irfanfadhullah** [HamedHojatian/HBF-Net#2]
Hello, thank you for the information on how to generate the unsupervised dataset. I want to ask another question, so I decided to open a new issue.
Is the process the same for generating a supervised learning dataset? For example, your previous paper "RSSI-Based HBF Design with Deep Learning" used a supervised dataset.
If the process is not the same, could you provide the information on how to generate that dataset?
Thank you

**Comment by HamedHojatian** [comment]
Yes, the process is same.However, since it is supervised learning, there would be the optimal values as target. Thus, the dataset consist of RSSI, CSI and optimal values.

**Comment by irfanfadhullah** [comment]
So, in order to get the optimal values of HB that using perfect CSI, we need to find it by using the steps in the Section II.B in the "RSSI-Based HBF Design with Deep Learning" paper right?

**Comment by HamedHojatian** [comment]
Yes or you can use III.C in "Unsupervised Deep Learning for Massive MIMO Hybrid Beamforming".
